### ISSUE TITLE
Xây dựng UI cho đề tài

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/AppDatMuaNoiThat#1]
- [x] Tìm hiểu về UI của app bán đồ nội thất
- [x] Thiết kế UI (hoặc lấy mẫu có sẵn về sửa lại)
- [x] Viết hướng dẫn chi tiết về UI
- [x] Nộp link cho các task đã làm được

**Comment by ChokeGuy** [comment]
[UI.docx](https://github.com/AnNgoIT/AppDatMuaNoiThat/files/11128985/UI.docx)
